<?php

namespace App\Services;

use App\Contracts\PersonRepositoryInterface;
use App\DTO\CreatePersonData;
use App\DTO\PersonAliasInputDTO;
use App\DTO\PersonDTO;
use App\DTO\UpdatePersonData;
use App\Exceptions\PersonException;
use App\Models\Person;
use App\Models\PersonAlias;
use App\Models\Project;
use Illuminate\Support\Collection;

class PersonService
{
    public function __construct(
        private readonly PersonRepositoryInterface $repository,
        private readonly PersonAliasGeneratorService $aliasGenerator,
    ) {}

    public function createPerson(CreatePersonData $data): Person
    {
        $this->assertProjectExists($data->projectId);

        $aliases = $this->aliasGenerator->generateForCreate($data);

        return $this->repository->store($data, $aliases);
    }

    public function updatePerson(string $uuid, UpdatePersonData $data): Person
    {
        $person = $this->requirePerson($uuid);

        $updatedPerson = $this->repository->update($person, $data);

        if ($data->regenerateAliases || $data->fullName !== null || $data->customAliases !== null) {
            $fullName = $data->fullName ?? $updatedPerson->full_name;
            $language = $data->primaryLanguage ?? $updatedPerson->primary_language;
            $customAliases = $data->customAliases ?? $this->extractCustomAliases($updatedPerson);

            $aliases = $this->aliasGenerator->generateForUpdate(
                fullName: $fullName,
                primaryLanguage: $language,
                customAliases: $customAliases,
            );

            $this->repository->replaceAutoGeneratedAliases($updatedPerson, $aliases);
            $updatedPerson = $this->requirePerson($uuid);
        }

        return $updatedPerson;
    }

    public function syncPersonAliases(string $uuid): Person
    {
        $person = $this->requirePerson($uuid);

        $aliases = $this->aliasGenerator->generateForUpdate(
            fullName: $person->full_name,
            primaryLanguage: $person->primary_language,
            customAliases: $this->extractCustomAliases($person),
        );

        $this->repository->replaceAutoGeneratedAliases($person, $aliases);

        return $this->requirePerson($uuid);
    }

    public function addCustomAlias(string $uuid, PersonAliasInputDTO $input): PersonAlias
    {
        $person = $this->requirePerson($uuid);

        return $this->repository->addCustomAlias($person, $input);
    }

    public function findPerson(string $uuid): ?Person
    {
        return $this->repository->findByUuid($uuid);
    }

    /**
     * @return Collection<int, Person>
     */
    public function listPersonsByProject(int $projectId, bool $activeOnly = true): Collection
    {
        return $this->repository->listByProject($projectId, $activeOnly);
    }

    public function toDto(Person $person): PersonDTO
    {
        $aliases = $person->aliases
            ->map(fn (PersonAlias $alias): \App\DTO\PersonAliasDTO => new \App\DTO\PersonAliasDTO(
                alias: $alias->alias,
                normalizedAlias: $alias->normalized_alias,
                type: $alias->type,
                language: $alias->language,
                isAutoGenerated: $alias->is_auto_generated,
                sourceAliasId: $alias->source_alias_id,
            ))
            ->values()
            ->all();

        return new PersonDTO(
            uuid: $person->uuid,
            projectId: $person->project_id,
            fullName: $person->full_name,
            primaryLanguage: $person->primary_language,
            isActive: $person->is_active,
            aliases: $aliases,
            notes: $person->notes,
            metadata: $person->metadata,
        );
    }

    private function requirePerson(string $uuid): Person
    {
        $person = $this->repository->findByUuid($uuid);

        if ($person === null) {
            throw new PersonException("Person [{$uuid}] was not found.");
        }

        return $person;
    }

    private function assertProjectExists(int $projectId): void
    {
        if (! Project::query()->whereKey($projectId)->exists()) {
            throw new PersonException("Project [{$projectId}] was not found.");
        }
    }

    /**
     * @return list<string>
     */
    private function extractCustomAliases(Person $person): array
    {
        return $person->aliases
            ->filter(fn (PersonAlias $alias): bool => $alias->type === \App\Enums\PersonAliasType::Alias && ! $alias->is_auto_generated)
            ->map(fn (PersonAlias $alias): string => $alias->alias)
            ->values()
            ->all();
    }
}
