<?php

namespace App\Services;

use App\DTO\CreatePersonData;
use App\DTO\PersonAliasDTO;
use App\DTO\UpdatePersonData;
use App\Enums\PersonAliasType;
use App\Enums\PersonLanguage;

class PersonAliasGeneratorService
{
    public function __construct(
        private readonly PersonNameNormalizer $normalizer,
        private readonly PersonTransliterationService $transliterationService,
        private readonly PersonTypoVariantGenerator $typoVariantGenerator,
    ) {}

    /**
     * @param  list<string>  $customAliases
     * @return list<PersonAliasDTO>
     */
    public function generateForCreate(CreatePersonData $data): array
    {
        return $this->generate(
            fullName: $data->fullName,
            primaryLanguage: $data->primaryLanguage,
            customAliases: $data->customAliases,
        );
    }

    /**
     * @param  list<string>  $customAliases
     * @return list<PersonAliasDTO>
     */
    public function generateForUpdate(
        string $fullName,
        PersonLanguage $primaryLanguage,
        array $customAliases,
    ): array {
        return $this->generate(
            fullName: $fullName,
            primaryLanguage: $primaryLanguage,
            customAliases: $customAliases,
        );
    }

    /**
     * @param  list<string>  $customAliases
     * @return list<PersonAliasDTO>
     */
    private function generate(
        string $fullName,
        PersonLanguage $primaryLanguage,
        array $customAliases,
    ): array {
        $aliases = [];
        $seen = [];

        $this->appendAlias(
            aliases: $aliases,
            seen: $seen,
            alias: $fullName,
            type: PersonAliasType::FullName,
            language: $primaryLanguage,
            isAutoGenerated: true,
        );

        foreach ($customAliases as $customAlias) {
            $this->appendAlias(
                aliases: $aliases,
                seen: $seen,
                alias: $customAlias,
                type: PersonAliasType::Alias,
                language: PersonLanguage::Custom,
                isAutoGenerated: false,
            );
        }

        if ((bool) config('person.transliteration.enabled', true)) {
            $this->appendTransliterations($aliases, $seen, $fullName, $primaryLanguage);

            foreach ($customAliases as $customAlias) {
                $this->appendTransliterations($aliases, $seen, $customAlias, PersonLanguage::Custom);
            }
        }

        $this->appendTypoVariants($aliases, $seen, $fullName, $primaryLanguage);

        foreach ($customAliases as $customAlias) {
            $this->appendTypoVariants($aliases, $seen, $customAlias, PersonLanguage::Custom);
        }

        return $aliases;
    }

    /**
     * @param  list<PersonAliasDTO>  $aliases
     * @param  list<string>  $seen
     */
    private function appendTransliterations(
        array &$aliases,
        array &$seen,
        string $sourceAlias,
        PersonLanguage $sourceLanguage,
    ): void {
        foreach ($this->transliterationService->generateVariants($sourceAlias, $this->normalizer) as $variant) {
            $targetLanguage = $this->normalizer->containsCyrillic($variant)
                ? PersonLanguage::Russian
                : PersonLanguage::English;

            $this->appendAlias(
                aliases: $aliases,
                seen: $seen,
                alias: $variant,
                type: PersonAliasType::Transliteration,
                language: $targetLanguage,
                isAutoGenerated: true,
            );
        }
    }

    /**
     * @param  list<PersonAliasDTO>  $aliases
     * @param  list<string>  $seen
     */
    private function appendTypoVariants(
        array &$aliases,
        array &$seen,
        string $sourceAlias,
        PersonLanguage $language,
    ): void {
        foreach ($this->typoVariantGenerator->generate($sourceAlias) as $variant) {
            $this->appendAlias(
                aliases: $aliases,
                seen: $seen,
                alias: $variant,
                type: PersonAliasType::TypoVariant,
                language: $language,
                isAutoGenerated: true,
            );
        }
    }

    /**
     * @param  list<PersonAliasDTO>  $aliases
     * @param  list<string>  $seen
     */
    private function appendAlias(
        array &$aliases,
        array &$seen,
        string $alias,
        PersonAliasType $type,
        PersonLanguage $language,
        bool $isAutoGenerated,
    ): void {
        $trimmed = trim($alias);

        if ($trimmed === '') {
            return;
        }

        $normalized = $this->normalizer->normalize($trimmed);
        $dedupeKey = $normalized.'|'.$type->value;

        if (in_array($dedupeKey, $seen, true)) {
            return;
        }

        $seen[] = $dedupeKey;
        $aliases[] = new PersonAliasDTO(
            alias: $trimmed,
            normalizedAlias: $normalized,
            type: $type,
            language: $language,
            isAutoGenerated: $isAutoGenerated,
        );
    }
}
