<?php

namespace App\DTO;

use App\Enums\PersonLanguage;

readonly class PersonAliasDTO
{
    public function __construct(
        public string $alias,
        public string $normalizedAlias,
        public \App\Enums\PersonAliasType $type,
        public PersonLanguage $language,
        public bool $isAutoGenerated = false,
        public ?int $sourceAliasId = null,
    ) {}
}
