<?php

namespace Tests\Feature\Person;

use App\Contracts\PersonRepositoryInterface;
use App\DTO\CreatePersonData;
use App\DTO\PersonAliasDTO;
use App\DTO\PersonAliasInputDTO;
use App\Enums\PersonAliasType;
use App\Enums\PersonLanguage;
use App\Models\Person;
use App\Models\Project;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class PersonRepositoryTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function it_stores_person_with_aliases(): void
    {
        $project = Project::query()->create([
            'name' => 'Repo Project',
            'slug' => 'repo-project',
            'is_active' => true,
        ]);

        $repository = $this->app->make(PersonRepositoryInterface::class);

        $person = $repository->store(
            new CreatePersonData(
                projectId: $project->id,
                fullName: 'John Smith',
                primaryLanguage: PersonLanguage::English,
            ),
            [
                new PersonAliasDTO(
                    alias: 'John Smith',
                    normalizedAlias: 'john smith',
                    type: PersonAliasType::FullName,
                    language: PersonLanguage::English,
                    isAutoGenerated: true,
                ),
            ],
        );

        $this->assertSame('John Smith', $person->full_name);
        $this->assertCount(1, $person->aliases);
        $this->assertSame('john smith', $person->aliases->first()?->normalized_alias);
    }

    #[Test]
    public function it_adds_custom_alias_and_lists_persons_by_project(): void
    {
        $project = Project::query()->create([
            'name' => 'Alias Project',
            'slug' => 'alias-project',
            'is_active' => true,
        ]);

        $repository = $this->app->make(PersonRepositoryInterface::class);

        $person = $repository->store(
            new CreatePersonData(
                projectId: $project->id,
                fullName: 'Jane Doe',
                primaryLanguage: PersonLanguage::English,
            ),
            [],
        );

        $alias = $repository->addCustomAlias($person, new PersonAliasInputDTO(
            alias: 'J. Doe',
            language: PersonLanguage::Custom,
        ));

        $this->assertSame(PersonAliasType::Alias, $alias->type);
        $this->assertFalse($alias->is_auto_generated);
        $this->assertCount(1, $repository->listByProject($project->id));
    }

    #[Test]
    public function it_replaces_auto_generated_aliases(): void
    {
        $project = Project::query()->create([
            'name' => 'Sync Project',
            'slug' => 'sync-project',
            'is_active' => true,
        ]);

        $repository = $this->app->make(PersonRepositoryInterface::class);

        $person = $repository->store(
            new CreatePersonData(
                projectId: $project->id,
                fullName: 'Old Name',
                primaryLanguage: PersonLanguage::English,
            ),
            [
                new PersonAliasDTO(
                    alias: 'Old Name',
                    normalizedAlias: 'old name',
                    type: PersonAliasType::FullName,
                    language: PersonLanguage::English,
                    isAutoGenerated: true,
                ),
            ],
        );

        $repository->addCustomAlias($person, new PersonAliasInputDTO(
            alias: 'Custom Alias',
            language: PersonLanguage::Custom,
        ));

        $repository->replaceAutoGeneratedAliases($person, [
            new PersonAliasDTO(
                alias: 'New Name',
                normalizedAlias: 'new name',
                type: PersonAliasType::FullName,
                language: PersonLanguage::English,
                isAutoGenerated: true,
            ),
            new PersonAliasDTO(
                alias: 'New Typo',
                normalizedAlias: 'new typo',
                type: PersonAliasType::TypoVariant,
                language: PersonLanguage::English,
                isAutoGenerated: true,
            ),
        ]);

        $person->refresh()->load('aliases');

        $this->assertTrue($person->aliases->contains(
            fn ($alias): bool => $alias->alias === 'Custom Alias' && $alias->type === PersonAliasType::Alias,
        ));
        $this->assertTrue($person->aliases->contains(
            fn ($alias): bool => $alias->alias === 'New Name' && $alias->type === PersonAliasType::FullName,
        ));
        $this->assertFalse($person->aliases->contains(
            fn ($alias): bool => $alias->alias === 'Old Name',
        ));
    }

    #[Test]
    public function it_finds_person_by_uuid(): void
    {
        $project = Project::query()->create([
            'name' => 'Find Project',
            'slug' => 'find-project',
            'is_active' => true,
        ]);

        $repository = $this->app->make(PersonRepositoryInterface::class);

        $person = Person::query()->create([
            'project_id' => $project->id,
            'full_name' => 'Lookup Person',
            'primary_language' => PersonLanguage::English,
            'is_active' => true,
        ]);

        $found = $repository->findByUuid($person->uuid);

        $this->assertNotNull($found);
        $this->assertSame($person->id, $found?->id);
    }
}
