<?php

namespace App\Contracts;

use App\DTO\CreatePersonData;
use App\DTO\PersonAliasDTO;
use App\DTO\PersonAliasInputDTO;
use App\DTO\UpdatePersonData;
use App\Models\Person;
use App\Models\PersonAlias;
use Illuminate\Support\Collection;

interface PersonRepositoryInterface
{
    public function store(CreatePersonData $data, array $aliases): Person;

    public function update(Person $person, UpdatePersonData $data): Person;

    public function findByUuid(string $uuid): ?Person;

    /**
     * @return Collection<int, Person>
     */
    public function listByProject(int $projectId, bool $activeOnly = true): Collection;

    /**
     * @param  list<PersonAliasDTO>  $aliases
     */
    public function replaceAutoGeneratedAliases(Person $person, array $aliases): void;

    public function addCustomAlias(Person $person, PersonAliasInputDTO $input): PersonAlias;

    public function removeAlias(PersonAlias $alias): void;
}
