<?php

namespace App\Repositories;

use App\Contracts\PersonRepositoryInterface;
use App\DTO\CreatePersonData;
use App\DTO\PersonAliasDTO;
use App\DTO\PersonAliasInputDTO;
use App\DTO\UpdatePersonData;
use App\Enums\PersonAliasType;
use App\Enums\PersonLanguage;
use App\Models\Person;
use App\Models\PersonAlias;
use App\Services\PersonNameNormalizer;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class PersonRepository implements PersonRepositoryInterface
{
    public function __construct(
        private readonly PersonNameNormalizer $normalizer,
    ) {}

    public function store(CreatePersonData $data, array $aliases): Person
    {
        return DB::transaction(function () use ($data, $aliases): Person {
            $person = Person::query()->create([
                'project_id' => $data->projectId,
                'full_name' => trim($data->fullName),
                'primary_language' => $data->primaryLanguage->value,
                'is_active' => $data->isActive,
                'notes' => $data->notes,
                'metadata' => $data->metadata,
            ]);

            $this->persistAliases($person, $aliases);

            return $person->load('aliases');
        });
    }

    public function update(Person $person, UpdatePersonData $data): Person
    {
        return DB::transaction(function () use ($person, $data): Person {
            $attributes = array_filter([
                'full_name' => $data->fullName !== null ? trim($data->fullName) : null,
                'primary_language' => $data->primaryLanguage?->value,
                'is_active' => $data->isActive,
                'notes' => $data->notes,
                'metadata' => $data->metadata,
            ], fn (mixed $value): bool => $value !== null);

            if ($attributes !== []) {
                $person->update($attributes);
            }

            return $person->fresh(['aliases']) ?? $person;
        });
    }

    public function findByUuid(string $uuid): ?Person
    {
        return Person::query()
            ->with('aliases')
            ->where('uuid', $uuid)
            ->first();
    }

    public function listByProject(int $projectId, bool $activeOnly = true): Collection
    {
        $query = Person::query()
            ->with('aliases')
            ->where('project_id', $projectId)
            ->orderBy('full_name');

        if ($activeOnly) {
            $query->where('is_active', true);
        }

        return $query->get();
    }

    public function replaceAutoGeneratedAliases(Person $person, array $aliases): void
    {
        DB::transaction(function () use ($person, $aliases): void {
            PersonAlias::query()
                ->where('person_id', $person->id)
                ->where('is_auto_generated', true)
                ->delete();

            $this->persistAliases($person, $aliases);
        });
    }

    public function addCustomAlias(Person $person, PersonAliasInputDTO $input): PersonAlias
    {
        $alias = trim($input->alias);

        return PersonAlias::query()->create([
            'person_id' => $person->id,
            'alias' => $alias,
            'normalized_alias' => $this->normalizer->normalize($alias),
            'type' => PersonAliasType::Alias->value,
            'language' => $input->language->value,
            'is_auto_generated' => false,
        ]);
    }

    public function removeAlias(PersonAlias $alias): void
    {
        $alias->delete();
    }

    /**
     * @param  list<PersonAliasDTO>  $aliases
     */
    private function persistAliases(Person $person, array $aliases): void
    {
        foreach ($aliases as $alias) {
            PersonAlias::query()->updateOrCreate(
                [
                    'person_id' => $person->id,
                    'normalized_alias' => $alias->normalizedAlias,
                    'type' => $alias->type->value,
                ],
                [
                    'alias' => $alias->alias,
                    'language' => $alias->language->value,
                    'source_alias_id' => $alias->sourceAliasId,
                    'is_auto_generated' => $alias->isAutoGenerated,
                ],
            );
        }
    }
}
